import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'ky';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    // Language names
    'language.ky': 'Кыргызча',
    'language.ru': 'Русский',
    'language.en': 'English',
    
    // Navigation
    'nav.home': 'Главная',
    'nav.teachers': 'Учителя',
    'nav.schools': 'Школы',
    'nav.vacancies': 'Вакансии',
    'nav.messages': 'Сообщения',
    'nav.profile': 'Профиль',
    'nav.dashboard': 'Панель управления',
    'nav.login': 'Войти',
    'nav.register': 'Регистрация',
    'nav.logout': 'Выйти',
    'nav.about': 'О нас',
    'nav.navigation': 'Навигация',
    
    // Common
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.create': 'Создать',
    'common.search': 'Поиск',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.close': 'Закрыть',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.submit': 'Отправить',
    'common.more': 'Подробнее',
    'common.reset': 'Сбросить',
    
    // Brand
    'brand.name': 'TeacherConnect KG',
    'brand.description': 'Платформа для связи учителей и школ в Кыргызстане',
    
    // Auth Messages
    'auth.login': 'Вход',
    'auth.register': 'Регистрация',
    'auth.loginWithGoogle': 'Войти через Google',
    'auth.registerWithGoogle': 'Зарегистрироваться через Google',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Подтвердите пароль',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.alreadyHaveAccount': 'Уже есть аккаунт?',
    'auth.dontHaveAccount': 'Нет аккаунта?',
    'auth.loginError': 'Ошибка входа',
    'auth.registerError': 'Ошибка регистрации',
    'auth.userType': 'Тип пользователя',
    'auth.teacher': 'Учитель',
    'auth.school': 'Школа',
    'auth.email': 'Email',
    'auth.submit': 'Войти',
    'auth.register.submit': 'Зарегистрироваться',
    'auth.loggingIn': 'Вход...',
    'auth.registering': 'Регистрация...',
    'auth.loginDescription': 'Войдите в аккаунт для доступа к платформе',
    'auth.orLoginWithEmail': 'Или войдите через email',
    'auth.loginSuccess': 'Вход выполнен успешно!',
    'auth.welcomeMessage': 'Добро пожаловать на платформу',
    'auth.welcomeToDashboard': 'Добро пожаловать в панель управления',
    'auth.invalidCredentials': 'Неверный email или пароль',
    'auth.emailNotConfirmed': 'Подтвердите email для входа',
    'auth.passwordReset': 'Восстановление пароля',
    'auth.emailAddress': 'Email адрес',
    'auth.sendResetLink': 'Отправить ссылку для сброса',
    'auth.emailSent': 'Письмо отправлено',
    'auth.emailSentDescription': 'Проверьте почту для сброса пароля',
    'auth.emailSentSuccess': 'Письмо отправлено!',
    'auth.checkEmailForReset': 'Проверьте почту {email} и перейдите по ссылке для сброса пароля',
    'auth.authorizationRequired': 'Требуется авторизация',
    'auth.pleaseLoginForNotifications': 'Пожалуйста, войдите в систему для доступа к уведомлениям',
    'auth.confirmationEmailSent': 'Мы отправили ссылку подтверждения на ваш email. Пожалуйста, проверьте почту и кликните по ссылке для завершения регистрации.',
    'auth.registrationSuccess': 'Регистрация успешна!',
    'auth.checkEmailForConfirmation': 'Проверьте email для подтверждения аккаунта.',
    'auth.registrationFailed': 'Произошла ошибка при регистрации',
    'auth.googleAuthError': 'Не удалось войти через Google',
    'auth.accountType': 'Тип аккаунта',
    'auth.fullName': 'Полное имя',
    'auth.schoolName': 'Название школы',
    'auth.signInWithGoogle': 'Войти через Google',
    'auth.registerAs': 'Зарегистрироваться как {userType}',
    'auth.orUseEmail': 'Или используйте email',
    'auth.signIn': 'Войти',
    'auth.emailSentError': 'Не удалось отправить письмо',
    
    // Dashboard
    'dashboard.profile': 'Профиль',
    'dashboard.vacancies': 'Вакансии',
    'dashboard.applications': 'Заявки',
    'dashboard.teachers': 'Учителя',
    'dashboard.messages': 'Сообщения',
    'dashboard.settings': 'Настройки',
    
    // Vacancy Management
    'vacancy.title': 'Название вакансии',
    'vacancy.description': 'Описание вакансии',
    'vacancy.subject': 'Предмет',
    'vacancy.location': 'Местоположение',
    'vacancy.salary': 'Зарплата',
    'vacancy.salaryFrom': 'Зарплата от',
    'vacancy.salaryTo': 'Зарплата до',
    'vacancy.employment': 'Тип занятости',
    'vacancy.experience': 'Требуемый опыт',
    'vacancy.deadline': 'Срок подачи заявок',
    'vacancy.requirements': 'Требования к кандидату',
    'vacancy.benefits': 'Преимущества работы',
    'vacancy.active': 'Активна',
    'vacancy.inactive': 'Неактивна',
    'vacancy.created': 'Вакансия создана',
    'vacancy.updated': 'Вакансия обновлена',
    'vacancy.deleted': 'Вакансия удалена',
    'vacancy.createNew': 'Новая вакансия',
    'vacancy.createFirst': 'Создать первую вакансию',
    'vacancy.noVacancies': 'У вас пока нет опубликованных вакансий',
    'vacancy.schoolVacancies': 'Вакансии школы',
    'vacancy.applications': 'Отклики',
    'vacancy.activate': 'Активировать',
    'vacancy.deactivate': 'Деактивировать',
    'vacancy.titleRequired': 'Название вакансии обязательно для заполнения',
    'vacancy.creating': 'Создание...',
    'vacancy.featureInDevelopment': 'Функция в разработке',
    'vacancy.editingFeature': 'Редактирование вакансий будет доступно в следующем обновлении',
    'vacancy.applicationsFeature': 'Просмотр откликов будет доступен в следующем обновлении',
    'vacancy.negotiable': 'По договоренности',
    'vacancy.from': 'от',
    'vacancy.upTo': 'до',
    'vacancy.notSpecified': 'Не указана',
    'vacancy.locationNotSpecified': 'Местоположение не указано',
    'vacancy.pageTitle': 'Вакансии для преподавателей',
    'vacancy.pageSubtitle': 'Найдите подходящую работу в образовательных учреждениях',
    'vacancy.searchPlaceholder': 'Поиск вакансий...',
    'vacancy.allTypes': 'Все типы',
    'vacancy.cityPlaceholder': 'Город...',
    
    // Employment Types
    'employment.fullTime': 'Полная занятость',
    'employment.partTime': 'Частичная занятость',
    'employment.contract': 'Контракт',
    'employment.temporary': 'Временная работа',
    
    // Profile
    'profile.fullName': 'Полное имя',
    'profile.email': 'Email',
    'profile.phone': 'Телефон',
    'profile.bio': 'О себе',
    'profile.education': 'Образование',
    'profile.experience': 'Опыт работы',
    'profile.skills': 'Навыки',
    'profile.languages': 'Языки',
    'profile.photo': 'Фотография профиля',
    'profile.uploadPhoto': 'Загрузить фото',
    'profile.changePhoto': 'Изменить фото',
    'profile.removePhoto': 'Удалить фото',
    'profile.photoUploaded': 'Фотография загружена',
    'profile.photoRemoved': 'Фотография удалена',
    'profile.uploadError': 'Ошибка загрузки фотографии',
    
    // School Profile
    'school.name': 'Название школы',
    'school.address': 'Адрес',
    'school.description': 'Описание школы',
    'school.type': 'Тип школы',
    'school.studentCount': 'Количество учеников',
    'school.foundedYear': 'Год основания',
    'school.website': 'Веб-сайт',
    'school.facilities': 'Удобства',
    'school.housingProvided': 'Предоставляется жилье',
    'school.students': 'учеников',
    
    // Maps & Address
    'address.searchPlaceholder': 'Введите адрес...',
    'address.selectLocation': 'Выберите местоположение на карте',
    'address.currentLocation': 'Текущее местоположение',
    'address.useCurrentLocation': 'Использовать текущее местоположение',
    'address.locationVerified': 'Местоположение подтверждено',
    'address.verifyLocation': 'Подтвердить местоположение',
    
    // Errors
    'error.general': 'Произошла ошибка. Попробуйте снова.',
    'error.network': 'Ошибка сети. Проверьте подключение к интернету.',
    'error.unauthorized': 'Доступ запрещен',
    'error.notFound': 'Страница не найдена',
    'error.pageNotFound': 'Извините, но запрашиваемая страница не существует.',
    'error.validation': 'Ошибка валидации данных',
    'error.fileUpload': 'Ошибка загрузки файла',
    'error.fileTooLarge': 'Файл слишком большой',
    'error.invalidFileType': 'Недопустимый тип файла',
    
    // CTA Section
    'cta.title': 'Присоединяйтесь к TeacherConnect!',
    'cta.subtitle': 'Создайте профиль или найдите работу в образовании',
    'cta.addVacancy': 'Добавить вакансию',
    'cta.findJob': 'Найти работу',
    
    // Teachers
    'teachers.header': 'Преподаватели и услуги',
    'teachers.subheader': 'Найдите квалифицированных преподавателей и их услуги',
    'teachers.tab': 'Преподаватели',
    'teachers.servicesTab': 'Услуги',
    'teachers.searchPlaceholder': 'Поиск по имени или специализации...',
    'teachers.servicesSearchPlaceholder': 'Поиск услуг...',
    'teachers.subjectPlaceholder': 'Предмет',
    'teachers.locationPlaceholder': 'Местоположение',
    'teachers.foundCount': 'Найдено {{count}} преподавателей',
    'teachers.servicesFoundCount': 'Найдено {{count}} услуг',
    'teachers.notFound': 'Преподаватели не найдены',
    'teachers.tryChangeSearch': 'Попробуйте изменить параметры поиска или опубликуйте свой профиль',
    'teachers.servicesNotFound': 'Услуги не найдены',
    'teachers.search': 'Поиск учителей',
    'teachers.advancedSearch': 'Расширенный поиск',
    'teachers.noTeachersFound': 'Учителя не найдены',
    'teachers.noTeachersDescription': 'В данный момент нет доступных учителей. Создайте вакансию, чтобы привлечь кандидатов.',
    'teachers.browseAllTeachers': 'Просмотреть всех учителей',
    
    // Applications
    'applications.title': 'Отклики на вакансии',
    'applications.description': 'Отклики учителей на размещенные вакансии',
    'applications.new': 'Новые',
    'applications.inProgress': 'В работе',
    'applications.archive': 'Архив',
    'applications.noNewApplications': 'Нет новых откликов',
    'applications.noApplicationsDescription': 'Когда учителя будут откликаться на ваши вакансии, они появятся здесь.',
    'applications.createVacancy': 'Создать вакансию',
    'applications.noInProgressApplications': 'Нет откликов в работе',
    'applications.noInProgressDescription': 'Отклики, которые вы обрабатываете, будут отображаться здесь.',
    'applications.noArchivedApplications': 'Нет архивных откликов',
    'applications.noArchivedDescription': 'Завершенные отклики будут перемещены в архив.',
    
    // Saved Items
    'savedItems.title': 'Избранное',
    'savedItems.description': 'Ваши сохраненные учителя и школы',
    'savedItems.searchPlaceholder': 'Поиск в избранном...',
    'savedItems.teachers': 'Учителя',
    'savedItems.schools': 'Школы',
    'savedItems.noSavedTeachers': 'Нет сохраненных учителей',
    'savedItems.noSavedTeachersDescription': 'Сохраняйте интересных учителей, чтобы быстро найти их позже.',
    'savedItems.browseTeachers': 'Найти учителей',
    'savedItems.noSavedSchools': 'Нет сохраненных школ',
    'savedItems.noSavedSchoolsDescription': 'Сохраняйте интересные школы, чтобы быстро найти их позже.',
    'savedItems.browseSchools': 'Найти школы',
    'savedItems.pleaseLoginForAccess': 'Пожалуйста, войдите в систему для доступа к избранному',
    
    // Home Page
    'home.hero.title': 'Найдите свою идеальную работу в образовании',
    'home.hero.subtitle': 'Платформа, которая соединяет талантливых преподавателей с лучшими образовательными учреждениями по всей стране',
    'home.hero.findTeachers': 'Найти преподавателей',
    'home.hero.findVacancies': 'Поиск вакансий',
    'home.stats.teachers': 'Квалифицированных преподавателей',
    'home.stats.schools': 'Образовательных учреждений',
    'home.stats.vacancies': 'Активных вакансий',
    'home.vacancies.title': 'Актуальные вакансии',
    'home.vacancies.subtitle': 'Свежие предложения от ведущих образовательных учреждений',
    'home.vacancies.viewAllVacancies': 'Посмотреть все вакансии',
    'home.teachers.title': 'Опытные преподаватели',
    'home.teachers.subtitle': 'Знакомьтесь с нашими талантливыми преподавателями',
    'home.teachers.viewAllTeachers': 'Посмотреть всех преподавателей',
    'home.schools.title': 'Ведущие образовательные учреждения',
    'home.schools.subtitle': 'Школы и учебные заведения, которые ищут талантливых преподавателей',
    'home.schools.viewAllSchools': 'Посмотреть все школы',
    
    // Currency
    'currency.som': 'с',
    
    // Teacher
    'teacher.nameNotSpecified': 'Имя не указано',
    'teacher.yearsOfExperience': 'лет опыта',
    
    // FAQ
    'faq.title': 'Часто задаваемые вопросы',
    'faq.subtitle': 'Ответы на популярные вопросы о платформе',
    'faq.frequentlyAsked': 'Часто задаваемые вопросы',
    'faq.createProfile.question': 'Как создать профиль?',
    'faq.createProfile.answer': 'Для создания профиля необходимо зарегистрироваться, затем заполнить все необходимые поля в личном кабинете. Учителя указывают свою специализацию, опыт работы, образование и предпочтения по работе. Школы заполняют информацию о своем образовательном учреждении.',
    'faq.findSchool.question': 'Как найти подходящую школу?',
    'faq.findSchool.answer': 'Используйте фильтры на странице "Школы", чтобы найти учебное заведение по местоположению, специализации и другим параметрам. Вы можете просматривать профили школ и их открытые вакансии.',
    'faq.applyVacancy.question': 'Как откликнуться на вакансию?',
    'faq.applyVacancy.answer': 'На странице вакансии нажмите на кнопку "Откликнуться". Школа получит уведомление о вашем отклике и сможет просмотреть ваш профиль. После этого с вами могут связаться для дальнейшего обсуждения.',
    'faq.contactSupport.question': 'Что делать, если нет ответа на отклик?',
    'faq.contactSupport.answer': 'Если школа не отвечает на ваш отклик в течение недели, вы можете отправить повторное сообщение через систему чата на платформе. Также рекомендуем продолжать поиск и откликаться на другие интересующие вас вакансии.',
    'faq.profileVisibility.question': 'Как удалить свой аккаунт?',
    'faq.profileVisibility.answer': 'Для удаления аккаунта перейдите в настройки профиля, выберите раздел "Удаление аккаунта" и следуйте инструкциям. Обратите внимание, что это действие необратимо, и все ваши данные будут удалены из системы.',
    'faq.safety.question': 'Могу ли я изменить тип аккаунта?',
    'faq.safety.answer': 'Нет, тип аккаунта (учитель или школа) выбирается при регистрации и не может быть изменен. Если вам необходимо сменить тип аккаунта, придется создать новую учетную запись.',
    
    // Support
    'support.title': 'Поддержка',
    'support.subtitle': 'Мы здесь, чтобы помочь вам с любыми вопросами',
    'support.contactForm': 'Контактная форма',
    'support.contactFormDescription': 'Заполните форму, и мы свяжемся с вами в ближайшее время',
    'support.name': 'Ваше имя',
    'support.namePlaceholder': 'Введите ваше имя',
    'support.email': 'Email',
    'support.emailPlaceholder': 'your@email.com',
    'support.subject': 'Тема',
    'support.subjectPlaceholder': 'Кратко опишите проблему',
    'support.message': 'Сообщение',
    'support.messagePlaceholder': 'Подробно опишите ваш вопрос или проблему',
    'support.sendMessage': 'Отправить сообщение',
    'support.sending': 'Отправка...',
    'support.messageSent': 'Сообщение отправлено',
    'support.responseTime': 'Мы ответим вам в ближайшее время',
    'support.contactInfo': 'Контактная информация',
    'support.contactInfoDescription': 'Свяжитесь с нами любым удобным способом',
    'support.emailSupport': 'Email поддержка',
    'support.liveChat': 'Онлайн чат',
    'support.liveChatDescription': 'Рабочие часы: 9:00 - 18:00 (Пн-Пт)',
    'support.documentation': 'Документация',
    'support.documentationDescription': 'Полезные статьи и руководства',
    'support.viewDocs': 'Посмотреть документацию',
    'support.commonIssues': 'Частые вопросы',
    'support.howToRegister': 'Как зарегистрироваться?',
    'support.howToCreateProfile': 'Как создать профиль?',
    'support.howToApply': 'Как откликнуться на вакансию?',
    'support.accountIssues': 'Проблемы с аккаунтом',
    
    // Footer
    'footer.information': 'Информация',
    'footer.support': 'Поддержка',
    'footer.privacyPolicy': 'Политика конфиденциальности',
    'footer.termsOfUse': 'Условия использования',
    'footer.contacts': 'Контакты',
    'footer.address': 'г. Бишкек, Кыргызская Республика',
    'footer.slogan': 'Соединяем учителей и школы по всей стране',
    'footer.schoolCatalog': 'Каталог школ',
    'footer.allRightsReserved': 'Все права защищены',
    
    // Notifications
    'notifications.title': 'Уведомления',
    'notifications.markAllAsRead': 'Отметить все как прочитанные',
    'notifications.markedAsRead': 'Отмечено как прочитанное',
    'notifications.allMarkedAsRead': 'Все уведомления отмечены как прочитанные',
    'notifications.welcomeTitle': 'Добро пожаловать на платформу!',
    'notifications.welcomeContent': 'Ваш аккаунт успешно создан. Заполните свой профиль, чтобы найти подходящие предложения.',
    'notifications.newMessageTitle': 'Новое сообщение от {sender}',
    'notifications.newMessageContent': 'У меня есть несколько вопросов по вакансии учителя физики.',
    
    // Contact Info
    'contact.email': 'teacherconnectkg@gmail.com',
    'contact.phone': '+996 XXX XXX XXX',
    
    // About page
    'about.title': 'О проекте',
    'about.subtitle': 'TeacherConnect Кыргызстан - платформа для соединения учителей и школ по всей стране',
    'about.mission.title': 'Наша миссия',
    'about.mission.paragraph1': 'Мы создали TeacherConnect KG, чтобы решить проблему нехватки квалифицированных педагогов в школах Кыргызстана. Наша платформа делает процесс поиска работы или сотрудников простым, прозрачным и эффективным.',
    'about.mission.paragraph2': 'Мы стремимся улучшить систему образования в стране, обеспечивая школы талантливыми педагогами, а учителям помогая найти работу, соответствующую их навыкам и предпочтениям.',
    'about.howItWorks.title': 'Как это работает',
    'about.forTeachers.title': 'Для учителей',
    'about.forTeachers.subtitle': 'Найдите работу своей мечты',
    'about.forTeachers.feature1': 'Создайте профессиональное портфолио',
    'about.forTeachers.feature2': 'Просматривайте актуальные вакансии',
    'about.forTeachers.feature3': 'Общайтесь напрямую со школами',
    'about.forTeachers.feature4': 'Фильтруйте по местоположению и условиям',
    'about.forSchools.title': 'Для школ',
    'about.forSchools.subtitle': 'Найдите идеальных кандидатов',
    'about.forSchools.feature1': 'Создайте профиль школы и вакансии',
    'about.forSchools.feature2': 'Просматривайте анкеты учителей',
    'about.forSchools.feature3': 'Оценивайте кандидатов',
    'about.forSchools.feature4': 'Находите специалистов по предметам',
    'about.advantages.title': 'Преимущества',
    'about.advantages.subtitle': 'Почему выбирают нас',
    'about.advantages.feature1': 'Проверенные анкеты и профили',
    'about.advantages.feature2': 'Интерфейс на трех языках',
    'about.advantages.feature3': 'Прямое общение без посредников',
    'about.advantages.feature4': 'Фокус на региональных потребностях',
    'about.learnMore': 'Узнать больше',
    'about.joinUs.title': 'Присоединяйтесь к нам сегодня!',
    'about.joinUs.description': 'Вместе мы можем улучшить систему образования Кыргызстана, соединяя талантливых учителей с нуждающимися в них школами. Зарегистрируйтесь сейчас и начните свой путь к успеху!',
    'about.faq.title': 'Частые вопросы',
    'about.faq.question1': 'Это бесплатно?',
    'about.faq.answer1': 'Да, базовое использование платформы бесплатно как для учителей, так и для школ. В будущем мы планируем добавить премиум-функции, но основные возможности останутся бесплатными.',
    'about.faq.question2': 'Как подтверждаются профили?',
    'about.faq.answer2': 'Мы используем систему проверки документов и верификации данных. После загрузки необходимых документов (дипломы, сертификаты) профиль получает статус "Проверенный".',
    'about.faq.question3': 'Можно ли использовать платформу на мобильном телефоне?',
    'about.faq.answer3': 'Да, наш сайт полностью адаптирован для мобильных устройств. Вы можете пользоваться всеми функциями с любого устройства с доступом в интернет.',
    'about.faq.viewAll': 'Смотреть все вопросы',
    
    // Schools page
    'schools.title': 'Школы',
    'schools.foundCount': 'Найдено {{count}} школ',
    'schools.searchPlaceholder': 'Поиск школ...',
    'schools.filters.city': 'Город',
    'schools.filters.district': 'Район',
    'schools.filters.schoolType': 'Тип школы',
    'schools.filters.housing': 'Жилье',
    'schools.filters.subjects': 'Предметы',
    'schools.filters.allCities': 'Все города',
    'schools.filters.allDistricts': 'Все районы',
    'schools.filters.allTypes': 'Все типы',
    'schools.filters.allOptions': 'Все варианты',
    'schools.filters.allSubjects': 'Все предметы',
    'schools.filters.withHousing': 'С жильем',
    'schools.filters.withoutHousing': 'Без жилья',
  },
  
  en: {
    // Language names
    'language.ky': 'Кыргызча',
    'language.ru': 'Русский',
    'language.en': 'English',
    
    // Navigation
    'nav.home': 'Home',
    'nav.teachers': 'Teachers',
    'nav.schools': 'Schools',
    'nav.vacancies': 'Vacancies',
    'nav.messages': 'Messages',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.about': 'About',
    'nav.navigation': 'Navigation',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.more': 'More',
    'common.reset': 'Reset',
    
    // Brand
    'brand.name': 'TeacherConnect KG',
    'brand.description': 'Platform for finding teaching jobs in Kyrgyzstan',
    
    // Auth Messages
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.loginWithGoogle': 'Login with Google',
    'auth.registerWithGoogle': 'Register with Google',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.loginError': 'Login Error',
    'auth.registerError': 'Registration Error',
    'auth.userType': 'User Type',
    'auth.teacher': 'Teacher',
    'auth.school': 'School',
    'auth.email': 'Email',
    'auth.submit': 'Login',
    'auth.register.submit': 'Register',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Registering...',
    'auth.loginDescription': 'Sign in to your account to access the platform',
    'auth.orLoginWithEmail': 'Or sign in with email',
    'auth.loginSuccess': 'Login successful!',
    'auth.welcomeMessage': 'Welcome to TeacherConnect KG',
    'auth.welcomeToDashboard': 'Welcome to your dashboard',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.emailNotConfirmed': 'Please confirm your email to login',
    'auth.passwordReset': 'Password Recovery',
    'auth.emailAddress': 'Email address',
    'auth.sendResetLink': 'Send reset link',
    'auth.emailSent': 'Email sent',
    'auth.emailSentDescription': 'Check your email for password reset',
    'auth.emailSentSuccess': 'Email sent!',
    'auth.checkEmailForReset': 'Check your email {email} and follow the link to reset your password',
    'auth.authorizationRequired': 'Authorization required',
    'auth.pleaseLoginForNotifications': 'Please log in to access notifications',
    'auth.confirmationEmailSent': 'We sent a confirmation link to your email. Please check your email and click the link to complete registration.',
    'auth.registrationSuccess': 'Registration successful!',
    'auth.checkEmailForConfirmation': 'Please check your email for confirmation',
    'auth.registrationFailed': 'Registration failed',
    'auth.googleAuthError': 'Failed to sign in with Google',
    'auth.accountType': 'Account type',
    'auth.fullName': 'Full Name',
    'auth.schoolName': 'School Name',
    'auth.signInWithGoogle': 'Sign in with Google',
    'auth.registerAs': 'Register as {userType}',
    'auth.orUseEmail': 'Or use email',
    'auth.signIn': 'Sign in',
    'auth.emailSentError': 'Failed to send email',
    
    // Dashboard
    'dashboard.profile': 'Profile',
    'dashboard.vacancies': 'Vacancies',
    'dashboard.applications': 'Applications',
    'dashboard.teachers': 'Teachers',
    'dashboard.messages': 'Messages',
    'dashboard.settings': 'Settings',
    
    // Vacancy Management
    'vacancy.title': 'Vacancy Title',
    'vacancy.description': 'Job Description',
    'vacancy.subject': 'Subject',
    'vacancy.location': 'Location',
    'vacancy.salary': 'Salary',
    'vacancy.salaryFrom': 'Salary From',
    'vacancy.salaryTo': 'Salary To',
    'vacancy.employment': 'Employment Type',
    'vacancy.experience': 'Required Experience',
    'vacancy.deadline': 'Application Deadline',
    'vacancy.requirements': 'Requirements',
    'vacancy.benefits': 'Benefits',
    'vacancy.active': 'Active',
    'vacancy.inactive': 'Inactive',
    'vacancy.created': 'Vacancy Created',
    'vacancy.updated': 'Vacancy Updated',
    'vacancy.deleted': 'Vacancy Deleted',
    'vacancy.createNew': 'New Vacancy',
    'vacancy.createFirst': 'Create First Vacancy',
    'vacancy.noVacancies': 'You have no published vacancies yet',
    'vacancy.schoolVacancies': 'School Vacancies',
    'vacancy.applications': 'Applications',
    'vacancy.activate': 'Activate',
    'vacancy.deactivate': 'Deactivate',
    'vacancy.titleRequired': 'Vacancy title is required',
    'vacancy.creating': 'Creating...',
    'vacancy.featureInDevelopment': 'Feature in Development',
    'vacancy.editingFeature': 'Vacancy editing will be available in the next update',
    'vacancy.applicationsFeature': 'Applications view will be available in the next update',
    'vacancy.negotiable': 'Negotiable',
    'vacancy.from': 'from',
    'vacancy.upTo': 'up to',
    'vacancy.notSpecified': 'Not specified',
    'vacancy.locationNotSpecified': 'Location not specified',
    'vacancy.pageTitle': 'Vacancies for Teachers',
    'vacancy.pageSubtitle': 'Find the right job in educational institutions',
    'vacancy.searchPlaceholder': 'Search vacancies...',
    'vacancy.allTypes': 'All types',
    'vacancy.cityPlaceholder': 'City...',
    
    // Employment Types
    'employment.fullTime': 'Full Time',
    'employment.partTime': 'Part Time',
    'employment.contract': 'Contract',
    'employment.temporary': 'Temporary',
    
    // Profile
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.bio': 'About',
    'profile.education': 'Education',
    'profile.experience': 'Experience',
    'profile.skills': 'Skills',
    'profile.languages': 'Languages',
    'profile.photo': 'Profile Photo',
    'profile.uploadPhoto': 'Upload Photo',
    'profile.changePhoto': 'Change Photo',
    'profile.removePhoto': 'Remove Photo',
    'profile.photoUploaded': 'Photo Uploaded',
    'profile.photoRemoved': 'Photo Removed',
    'profile.uploadError': 'Photo Upload Error',
    
    // School Profile
    'school.name': 'School Name',
    'school.address': 'Address',
    'school.description': 'School Description',
    'school.type': 'School Type',
    'school.studentCount': 'Student Count',
    'school.foundedYear': 'Founded Year',
    'school.website': 'Website',
    'school.facilities': 'Facilities',
    'school.housingProvided': 'Housing Provided',
    
    // Maps & Address
    'address.searchPlaceholder': 'Enter address...',
    'address.selectLocation': 'Select location on map',
    'address.currentLocation': 'Current Location',
    'address.useCurrentLocation': 'Use Current Location',
    'address.locationVerified': 'Location Verified',
    'address.verifyLocation': 'Verify Location',
    
    // Errors
    'error.general': 'An error occurred. Please try again.',
    'error.network': 'Network error. Check your internet connection.',
    'error.unauthorized': 'Access denied',
    'error.notFound': 'Page not found',
    'error.pageNotFound': 'Sorry, but the requested page does not exist.',
    'error.validation': 'Data validation error',
    'error.fileUpload': 'File upload error',
    'error.fileTooLarge': 'File too large',
    'error.invalidFileType': 'Invalid file type',
    
    // CTA Section
    'cta.title': 'Присоединяйтесь к TeacherConnect!',
    'cta.subtitle': 'Создайте профиль или найдите работу в образовании',
    'cta.addVacancy': 'Add Vacancy',
    'cta.findJob': 'Find Job',
    
    // Teachers
    'teachers.header': 'Teachers and Services',
    'teachers.subheader': 'Find qualified teachers and their services',
    'teachers.tab': 'Teachers',
    'teachers.servicesTab': 'Services',
    'teachers.searchPlaceholder': 'Search by name or specialization...',
    'teachers.servicesSearchPlaceholder': 'Search services...',
    'teachers.subjectPlaceholder': 'Subject',
    'teachers.locationPlaceholder': 'Location',
    'teachers.foundCount': '{{count}} teachers found',
    'teachers.servicesFoundCount': '{{count}} services found',
    'teachers.notFound': 'No teachers found',
    'teachers.tryChangeSearch': 'Try changing your search or publish your profile',
    'teachers.servicesNotFound': 'No services found',
    'teachers.search': 'Search teachers',
    'teachers.advancedSearch': 'Advanced Search',
    'teachers.noTeachersFound': 'No teachers found',
    'teachers.noTeachersDescription': 'No teachers available at the moment. Please create a vacancy to attract candidates.',
    'teachers.browseAllTeachers': 'View all teachers',
    
    // Applications
    'applications.title': 'Applications for Vacancies',
    'applications.description': 'Applications from teachers for posted vacancies',
    'applications.new': 'New',
    'applications.inProgress': 'In Progress',
    'applications.archive': 'Archive',
    'applications.noNewApplications': 'No new applications',
    'applications.noApplicationsDescription': 'When teachers apply for your vacancies, they will appear here.',
    'applications.createVacancy': 'Create a Vacancy',
    'applications.noInProgressApplications': 'No applications in progress',
    'applications.noInProgressDescription': 'Applications you are currently processing will appear here.',
    'applications.noArchivedApplications': 'No archived applications',
    'applications.noArchivedDescription': 'Completed applications will be moved to the archive.',
    
    // Saved Items
    'savedItems.title': 'Saved Items',
    'savedItems.description': 'Your saved teachers and schools',
    'savedItems.searchPlaceholder': 'Search saved...',
    'savedItems.teachers': 'Teachers',
    'savedItems.schools': 'Schools',
    'savedItems.noSavedTeachers': 'No saved teachers',
    'savedItems.noSavedTeachersDescription': 'Save your favorite teachers for quick access later.',
    'savedItems.browseTeachers': 'Find Teachers',
    'savedItems.noSavedSchools': 'No saved schools',
    'savedItems.noSavedSchoolsDescription': 'Save your favorite schools for quick access later.',
    'savedItems.browseSchools': 'Find Schools',
    'savedItems.pleaseLoginForAccess': 'Please log in to access your saved items',
    
    // Home Page
    'home.hero.title': 'Find Your Ideal Job in Education',
    'home.hero.subtitle': 'A platform that connects talented teachers with the best educational institutions across the country',
    'home.hero.findTeachers': 'Find Teachers',
    'home.hero.findVacancies': 'Search Vacancies',
    'home.stats.teachers': 'Qualified Teachers',
    'home.stats.schools': 'Educational Institutions',
    'home.stats.vacancies': 'Active Vacancies',
    'home.vacancies.title': 'Current Vacancies',
    'home.vacancies.subtitle': 'Fresh offers from leading educational institutions',
    'home.vacancies.viewAllVacancies': 'View All Vacancies',
    'home.teachers.title': 'Experienced Teachers',
    'home.teachers.subtitle': 'Meet our talented teachers',
    'home.teachers.viewAllTeachers': 'View All Teachers',
    'home.schools.title': 'Leading Educational Institutions',
    'home.schools.subtitle': 'Schools and educational institutions looking for talented teachers',
    'home.schools.viewAllSchools': 'View All Schools',
    
    // Currency
    'currency.som': 'som',
    
    // Teacher
    'teacher.nameNotSpecified': 'Name not specified',
    'teacher.yearsOfExperience': 'years of experience',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Answers to popular questions about the platform',
    'faq.frequentlyAsked': 'Frequently Asked Questions',
    'faq.createProfile.question': 'How to create a profile?',
    'faq.createProfile.answer': 'To create a profile, you need to register, then fill in all the required fields in your personal account. Teachers indicate their specialization, work experience, education and work preferences. Schools fill in information about their educational institution.',
    'faq.findSchool.question': 'How to find a suitable school?',
    'faq.findSchool.answer': 'Use filters on the "Schools" page to find an educational institution by location, specialization and other parameters. You can view school profiles and their open vacancies.',
    'faq.applyVacancy.question': 'How to apply for a vacancy?',
    'faq.applyVacancy.answer': 'On the vacancy page, click the "Apply" button. The school will receive a notification about your application and will be able to view your profile. After that, they may contact you for further discussion.',
    'faq.contactSupport.question': 'What to do if there is no response to the application?',
    'faq.contactSupport.answer': 'If the school does not respond to your application within a week, you can send a repeat message through the chat system on the platform. We also recommend continuing your search and applying for other vacancies that interest you.',
    'faq.profileVisibility.question': 'How to delete my account?',
    'faq.profileVisibility.answer': 'To delete an account, go to profile settings, select the "Delete Account" section and follow the instructions. Please note that this action is irreversible and all your data will be deleted from the system.',
    'faq.safety.question': 'Can I change my account type?',
    'faq.safety.answer': 'No, the account type (teacher or school) is chosen during registration and cannot be changed. If you need to change your account type, you will have to create a new account.',
    
    // Support
    'support.title': 'Support',
    'support.subtitle': 'We are here to help you with any questions',
    'support.contactForm': 'Contact Form',
    'support.contactFormDescription': 'Fill out the form and we will contact you soon',
    'support.name': 'Your Name',
    'support.namePlaceholder': 'Enter your name',
    'support.email': 'Email',
    'support.emailPlaceholder': 'your@email.com',
    'support.subject': 'Subject',
    'support.subjectPlaceholder': 'Briefly describe the issue',
    'support.message': 'Message',
    'support.messagePlaceholder': 'Describe your question or problem in detail',
    'support.sendMessage': 'Send Message',
    'support.sending': 'Sending...',
    'support.messageSent': 'Message Sent',
    'support.responseTime': 'We will respond to you soon',
    'support.contactInfo': 'Contact Information',
    'support.contactInfoDescription': 'Contact us in any convenient way',
    'support.emailSupport': 'Email Support',
    'support.liveChat': 'Live Chat',
    'support.liveChatDescription': 'Working hours: 9:00 - 18:00 (Mon-Fri)',
    'support.documentation': 'Documentation',
    'support.documentationDescription': 'Useful articles and guides',
    'support.viewDocs': 'View Documentation',
    'support.commonIssues': 'Common Issues',
    'support.howToRegister': 'How to register?',
    'support.howToCreateProfile': 'How to create a profile?',
    'support.howToApply': 'How to apply for a vacancy?',
    'support.accountIssues': 'Account issues',
    
    // Footer
    'footer.information': 'Information',
    'footer.support': 'Support',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfUse': 'Terms of Use',
    'footer.contacts': 'Contacts',
    'footer.address': 'Bishkek, Kyrgyz Republic',
    'footer.slogan': 'Connecting teachers and schools across the country',
    'footer.schoolCatalog': 'School Catalog',
    'footer.allRightsReserved': 'All rights reserved',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllAsRead': 'Mark all as read',
    'notifications.markedAsRead': 'Marked as read',
    'notifications.allMarkedAsRead': 'All notifications marked as read',
    'notifications.welcomeTitle': 'Welcome to TeacherConnect KG!',
    'notifications.welcomeContent': 'Your account has been successfully created. Fill out your profile to find suitable offers.',
    'notifications.newMessageTitle': 'New message from {sender}',
    'notifications.newMessageContent': 'I have several questions about the physics teacher vacancy.',
    
    // Contact Info
    'contact.email': 'teacherconnectkg@gmail.com',
    'contact.phone': '+996 XXX XXX XXX',
    
    // About page
    'about.title': 'About the Project',
    'about.subtitle': 'TeacherConnect Kyrgyzstan - a platform for connecting teachers and schools across the country',
    'about.mission.title': 'Our Mission',
    'about.mission.paragraph1': 'We created TeacherConnect KG to solve the shortage of qualified teachers in Kyrgyzstan schools. Our platform makes the process of finding jobs or employees simple, transparent, and effective.',
    'about.mission.paragraph2': 'We strive to improve the education system in the country by providing schools with talented teachers and helping teachers find jobs that match their skills and preferences.',
    'about.howItWorks.title': 'How it works',
    'about.forTeachers.title': 'For Teachers',
    'about.forTeachers.subtitle': 'Find your dream job',
    'about.forTeachers.feature1': 'Create a professional portfolio',
    'about.forTeachers.feature2': 'Browse current vacancies',
    'about.forTeachers.feature3': 'Communicate directly with schools',
    'about.forTeachers.feature4': 'Filter by location and conditions',
    'about.forSchools.title': 'For Schools',
    'about.forSchools.subtitle': 'Find ideal candidates',
    'about.forSchools.feature1': 'Create a school profile and vacancies',
    'about.forSchools.feature2': 'Browse teacher profiles',
    'about.forSchools.feature3': 'Evaluate candidates',
    'about.forSchools.feature4': 'Find specialists by subject',
    'about.advantages.title': 'Advantages',
    'about.advantages.subtitle': 'Why choose us',
    'about.advantages.feature1': 'Verified profiles and portfolios',
    'about.advantages.feature2': 'Interface in three languages',
    'about.advantages.feature3': 'Direct communication without intermediaries',
    'about.advantages.feature4': 'Focus on regional needs',
    'about.learnMore': 'Learn more',
    'about.joinUs.title': 'Join us today!',
    'about.joinUs.description': 'Together we can improve the education system of Kyrgyzstan by connecting talented teachers with schools that need them. Register now and start your path to success!',
    'about.faq.title': 'Frequently Asked Questions',
    'about.faq.question1': 'Is it free?',
    'about.faq.answer1': 'Yes, basic use of the platform is free for both teachers and schools. In the future, we plan to add premium features, but the main features will remain free.',
    'about.faq.question2': 'How are profiles verified?',
    'about.faq.answer2': 'We use a document verification system. After uploading the necessary documents (diplomas, certificates), the profile receives a "Verified" status.',
    'about.faq.question3': 'Can I use the platform on a mobile phone?',
    'about.faq.answer3': 'Yes, our site is fully adapted for mobile devices. You can use all features from any device with internet access.',
    'about.faq.viewAll': 'View all questions',
    
    // Schools page
    'schools.title': 'Schools',
    'schools.foundCount': 'Found {{count}} schools',
    'schools.searchPlaceholder': 'Search schools...',
    'schools.filters.city': 'City',
    'schools.filters.district': 'District',
    'schools.filters.schoolType': 'School Type',
    'schools.filters.housing': 'Housing',
    'schools.filters.subjects': 'Subjects',
    'schools.filters.allCities': 'All cities',
    'schools.filters.allDistricts': 'All districts',
    'schools.filters.allTypes': 'All types',
    'schools.filters.allOptions': 'All options',
    'schools.filters.allSubjects': 'All subjects',
    'schools.filters.withHousing': 'With housing',
    'schools.filters.withoutHousing': 'Without housing',
  },
  
  ky: {
    // Language names
    'language.ky': 'Кыргызча',
    'language.ru': 'Русский',
    'language.en': 'English',
    
    // Navigation
    'nav.home': 'Башкы бет',
    'nav.teachers': 'Мугалимдер',
    'nav.schools': 'Мектептер',
    'nav.vacancies': 'Жумуш орундары',
    'nav.messages': 'Билдирүүлөр',
    'nav.profile': 'Профиль',
    'nav.dashboard': 'Башкаруу панели',
    'nav.login': 'Кирүү',
    'nav.register': 'Катталуу',
    'nav.logout': 'Чыгуу',
    'nav.about': 'Биз жөнүндө',
    'nav.navigation': 'Навигация',
    
    // Common
    'common.save': 'Сактоо',
    'common.cancel': 'Жокко чыгаруу',
    'common.delete': 'Өчүрүү',
    'common.edit': 'Өзгөртүү',
    'common.create': 'Түзүү',
    'common.search': 'Издөө',
    'common.loading': 'Жүктөлүүдө...',
    'common.error': 'Ката',
    'common.success': 'Ийгиликтүү',
    'common.yes': 'Ооба',
    'common.no': 'Жок',
    'common.close': 'Жабуу',
    'common.back': 'Артка',
    'common.next': 'Кийинки',
    'common.submit': 'Жөнөтүү',
    'common.more': 'Көбүрөөк',
    'common.reset': 'Тазалоо',
    
    // Brand
    'brand.name': 'TeacherConnect KG',
    'brand.description': 'Кыргызстанда мугалимдердин жумушун табуу платформасы',
    
    // Auth Messages
    'auth.login': 'Кирүү',
    'auth.register': 'Катталуу',
    'auth.loginWithGoogle': 'Google аркылуу кирүү',
    'auth.registerWithGoogle': 'Google аркылуу катталуу',
    'auth.password': 'Сыр сөз',
    'auth.confirmPassword': 'Сыр сөздү ырастоо',
    'auth.forgotPassword': 'Сыр сөздү унуттуңузбу?',
    'auth.alreadyHaveAccount': 'Аккаунтуңуз барбы?',
    'auth.dontHaveAccount': 'Аккаунтуңуз жокпу?',
    'auth.loginError': 'Кирүү катасы',
    'auth.registerError': 'Катталуу катасы',
    'auth.userType': 'Колдонуучу түрү',
    'auth.teacher': 'Мугалим',
    'auth.school': 'Мектеп',
    'auth.email': 'Электрондук почта',
    'auth.submit': 'Кирүү',
    'auth.register.submit': 'Катталуу',
    'auth.loggingIn': 'Кирүүдө...',
    'auth.registering': 'Катталууда...',
    'auth.loginDescription': 'Платформага кирүү үчүн аккаунтуңузга кириңиз',
    'auth.orLoginWithEmail': 'Же электрондук почта аркылуу кириңиз',
    'auth.loginSuccess': 'Кирүү ийгиликтүү!',
    'auth.welcomeMessage': 'TeacherConnect KG\'га кош келиңиз',
    'auth.welcomeToDashboard': 'Башкаруу панелиңизге кош келиңиз',
    'auth.invalidCredentials': 'Жараксыз электрондук почта же сыр сөз',
    'auth.emailNotConfirmed': 'Кирүү үчүн электрондук почтаңызды ырастаңыз',
    'auth.passwordReset': 'Сыр сөздү калыбына келтирүү',
    'auth.emailAddress': 'Электрондук почта дареги',
    'auth.sendResetLink': 'Калыбына келтирүү шилтемесин жөнөтүү',
    'auth.emailSent': 'Электрондук почта жөнөтүлдү',
    'auth.emailSentDescription': 'Сыр сөздү калыбына келтирүү үчүн электрондук почтаңызды текшериңиз',
    'auth.emailSentSuccess': 'Электрондук почта жөнөтүлдү!',
    'auth.checkEmailForReset': 'Электрондук почтаңызды {email} текшериңиз жана сыр сөздү калыбына келтирүү үчүн шилтемени басыңыз',
    'auth.authorizationRequired': 'Авторизация талап кылынат',
    'auth.pleaseLoginForNotifications': 'Билдирүүлөргө кирүү үчүн системага кириңиз',
    'auth.confirmationEmailSent': 'Биз сиздин электрондук почтаңызга ырастоо шилтемесин жөнөттүк. Электрондук почтаңызды текшериңиз жана катталууну аяктоо үчүн шилтемени басыңыз.',
    'auth.registrationSuccess': 'Регистрация ийгиликтүү!',
    'auth.checkEmailForConfirmation': 'Электрондук почтаңызды текшериңиз жана катталууну аяктоо үчүн шилтемени басыңыз.',
    'auth.registrationFailed': 'Регистрацияда ката кетти',
    'auth.googleAuthError': 'Google аркылуу кирүү катасы',
    'auth.accountType': 'Аккаунт түрү',
    'auth.fullName': 'Толук аты',
    'auth.schoolName': 'Мектептин аталышы',
    'auth.signInWithGoogle': 'Google аркылуу кирүү',
    'auth.registerAs': 'Катталуу үчүн {userType}',
    'auth.orUseEmail': 'Же электрондук почта аркылуу кириңиз',
    'auth.signIn': 'Кирүү',
    'auth.emailSentError': 'Письмо жөнөтүлдү',
    
    // Dashboard
    'dashboard.profile': 'Профиль',
    'dashboard.vacancies': 'Вакансиялар',
    'dashboard.applications': 'Арыздар',
    'dashboard.teachers': 'Мугалимдер',
    'dashboard.messages': 'Билдирүүлөр',
    'dashboard.settings': 'Параметрлер',
    
    // Vacancy Management
    'vacancy.title': 'Вакансиянын аталышы',
    'vacancy.description': 'Жумуштун сыпаттамасы',
    'vacancy.subject': 'Предмет',
    'vacancy.location': 'Жайгашкан жери',
    'vacancy.salary': 'Айлык акы',
    'vacancy.salaryFrom': 'Айлык акы башынан',
    'vacancy.salaryTo': 'Айлык акы чейин',
    'vacancy.employment': 'Жумуш түрү',
    'vacancy.experience': 'Талап кылынган тажрыйба',
    'vacancy.deadline': 'Арыз берүү мөөнөтү',
    'vacancy.requirements': 'Талаптар',
    'vacancy.benefits': 'Артыкчылыктар',
    'vacancy.active': 'Активдүү',
    'vacancy.inactive': 'Активдүү эмес',
    'vacancy.created': 'Вакансия түзүлдү',
    'vacancy.updated': 'Вакансия жаңыртылды',
    'vacancy.deleted': 'Вакансия өчүрүлдү',
    'vacancy.createNew': 'Жаңы вакансия',
    'vacancy.createFirst': 'Биринчи вакансияны түзүү',
    'vacancy.noVacancies': 'Сизде азырынча жарыяланган вакансиялар жок',
    'vacancy.schoolVacancies': 'Мектептин вакансиялары',
    'vacancy.applications': 'Арыздар',
    'vacancy.activate': 'Активдештирүү',
    'vacancy.deactivate': 'Активдештирбөө',
    'vacancy.titleRequired': 'Вакансиянын аталышы милдеттүү',
    'vacancy.creating': 'Түзүлүүдө...',
    'vacancy.featureInDevelopment': 'Функция иштелип жатат',
    'vacancy.editingFeature': 'Вакансияларды өзгөртүү кийинки жаңыртууда жеткиликтүү болот',
    'vacancy.applicationsFeature': 'Арыздарды көрүү кийинки жаңыртууда жеткиликтүү болот',
    'vacancy.negotiable': 'Келишим боюнча',
    'vacancy.from': 'башынан',
    'vacancy.upTo': 'чейин',
    'vacancy.notSpecified': 'Көрсөтүлгөн эмес',
    'vacancy.locationNotSpecified': 'Жайгашкан жери көрсөтүлгөн эмес',
    'vacancy.pageTitle': 'Мугалимдер үчүн жумуш орундары',
    'vacancy.pageSubtitle': 'Билим берүү мекемелеринде ылайыктуу жумуш табыңыз',
    'vacancy.searchPlaceholder': 'Жумуш орундарын издөө...',
    'vacancy.allTypes': 'Бардык түрлөрү',
    'vacancy.cityPlaceholder': 'Шаар...',
    
    // Employment Types
    'employment.fullTime': 'Толук жумуш күнү',
    'employment.partTime': 'Жарым жумуш күнү',
    'employment.contract': 'Контракт',
    'employment.temporary': 'Убактылуу жумуш',
    
    // Profile
    'profile.fullName': 'Толук аты',
    'profile.email': 'Электрондук почта',
    'profile.phone': 'Телефон',
    'profile.bio': 'Өзү жөнүндө',
    'profile.education': 'Билими',
    'profile.experience': 'Тажрыйбасы',
    'profile.skills': 'Көндүмдөрү',
    'profile.languages': 'Тилдери',
    'profile.photo': 'Профиль сүрөтү',
    'profile.uploadPhoto': 'Сүрөт жүктөө',
    'profile.changePhoto': 'Сүрөт өзгөртүү',
    'profile.removePhoto': 'Сүрөт өчүрүү',
    'profile.photoUploaded': 'Сүрөт жүктөлдү',
    'profile.photoRemoved': 'Сүрөт өчүрүлдү',
    'profile.uploadError': 'Сүрөт жүктөө катасы',
    
    // School Profile
    'school.name': 'Мектептин аталышы',
    'school.address': 'Дареги',
    'school.description': 'Мектептин сыпаттамасы',
    'school.type': 'Мектептин түрү',
    'school.studentCount': 'Окуучулардын саны',
    'school.foundedYear': 'Түзүлгөн жылы',
    'school.website': 'Веб-сайт',
    'school.facilities': 'Шарттар',
    'school.housingProvided': 'Турак жай берилет',
    'school.students': 'окуучу',
    
    // Maps & Address
    'address.searchPlaceholder': 'Даректи киргизиңиз...',
    'address.selectLocation': 'Картадан жерди тандаңыз',
    'address.currentLocation': 'Учурдагы жер',
    'address.useCurrentLocation': 'Учурдагы жерди колдонуу',
    'address.locationVerified': 'Жер ырасталды',
    'address.verifyLocation': 'Жерди ырастоо',
    
    // Errors
    'error.general': 'Ката кетти. Кайра аракет кылыңыз.',
    'error.network': 'Тармак катасы. Интернет байланышыңызды текшериңиз.',
    'error.unauthorized': 'Кирүүгө тыюу салынган',
    'error.notFound': 'Бет табылган жок',
    'error.pageNotFound': 'Кечиресиз, суралган бет жок.',
    'error.validation': 'Маалыматтарды текшерүү катасы',
    'error.fileUpload': 'Файл жүктөө катасы',
    'error.fileTooLarge': 'Файл өтө чоң',
    'error.invalidFileType': 'Жараксыз файл түрү',
    
    // CTA Section
    'cta.title': 'Присоединяйтесь к TeacherConnect!',
    'cta.subtitle': 'Создайте профиль или найдите работу в образовании',
    'cta.addVacancy': 'Вакансия кошуу',
    'cta.findJob': 'Жумуш табуу',
    
    // Teachers
    'teachers.header': 'Мугалимдер жана кызматтар',
    'teachers.subheader': 'Квалификациялуу мугалимдерди жана алардын кызматтарын табыңыз',
    'teachers.tab': 'Мугалимдер',
    'teachers.servicesTab': 'Кызматтар',
    'teachers.searchPlaceholder': 'Аты же адистиги боюнча издөө...',
    'teachers.servicesSearchPlaceholder': 'Кызматтарды издөө...',
    'teachers.subjectPlaceholder': 'Предмет',
    'teachers.locationPlaceholder': 'Жайгашкан жери',
    'teachers.foundCount': '{{count}} мугалим табылды',
    'teachers.servicesFoundCount': '{{count}} кызмат табылды',
    'teachers.notFound': 'Мугалимдер табылган жок',
    'teachers.tryChangeSearch': 'Издөө параметрлерин өзгөртүп көрүңүз же профилиңизди жарыялаңыз',
    'teachers.servicesNotFound': 'Кызматтар табылган жок',
    'teachers.search': 'Поиск учителей',
    'teachers.advancedSearch': 'Расширенный поиск',
    'teachers.noTeachersFound': 'Учителя не найдены',
    'teachers.noTeachersDescription': 'В данный момент нет доступных учителей. Создайте вакансию, чтобы привлечь кандидатов.',
    'teachers.browseAllTeachers': 'Просмотреть всех учителей',
    
    // Applications
    'applications.title': 'Отклики на вакансии',
    'applications.description': 'Отклики учителей на размещенные вакансии',
    'applications.new': 'Новые',
    'applications.inProgress': 'В работе',
    'applications.archive': 'Архив',
    'applications.noNewApplications': 'Нет новых откликов',
    'applications.noApplicationsDescription': 'Когда учителя будут откликаться на ваши вакансии, они появятся здесь.',
    'applications.createVacancy': 'Создать вакансию',
    'applications.noInProgressApplications': 'Нет откликов в работе',
    'applications.noInProgressDescription': 'Отклики, которые вы обрабатываете, будут отображаться здесь.',
    'applications.noArchivedApplications': 'Нет архивных откликов',
    'applications.noArchivedDescription': 'Завершенные отклики будут перемещены в архив.',
    
    // Saved Items
    'savedItems.title': 'Избранное',
    'savedItems.description': 'Ваши сохраненные учителя и школы',
    'savedItems.searchPlaceholder': 'Поиск в избранном...',
    'savedItems.teachers': 'Учителя',
    'savedItems.schools': 'Школы',
    'savedItems.noSavedTeachers': 'Нет сохраненных учителей',
    'savedItems.noSavedTeachersDescription': 'Сохраняйте интересных учителей, чтобы быстро найти их позже.',
    'savedItems.browseTeachers': 'Найти учителей',
    'savedItems.noSavedSchools': 'Нет сохраненных школ',
    'savedItems.noSavedSchoolsDescription': 'Сохраняйте интересные школы, чтобы быстро найти их позже.',
    'savedItems.browseSchools': 'Найти школы',
    'savedItems.pleaseLoginForAccess': 'Пожалуйста, войдите в систему для доступа к избранному',
    
    // Home Page
    'home.hero.title': 'Билим берүүдө идеалдуу жумушуңузду табыңыз',
    'home.hero.subtitle': 'Жөндөмдүү мугалимдерди өлкө боюнча эң жакшы билим берүү мекемелери менен байланыштырган платформа',
    'home.hero.findTeachers': 'Мугалимдерди табуу',
    'home.hero.findVacancies': 'Вакансияларды издөө',
    'home.stats.teachers': 'Квалификациялуу мугалимдер',
    'home.stats.schools': 'Билим берүү мекемелери',
    'home.stats.vacancies': 'Активдүү вакансиялар',
    'home.vacancies.title': 'Учурдагы вакансиялар',
    'home.vacancies.subtitle': 'Жетекчи билим берүү мекемелеринен жаңы сунуштар',
    'home.vacancies.viewAllVacancies': 'Бардык вакансияларды көрүү',
    'home.teachers.title': 'Тажрыйбалуу мугалимдер',
    'home.teachers.subtitle': 'Биздин жөндөмдүү мугалимдерди таанышыңыз',
    'home.teachers.viewAllTeachers': 'Бардык мугалимдерди көрүү',
    'home.schools.title': 'Жетекчи билим берүү мекемелери',
    'home.schools.subtitle': 'Жөндөмдүү мугалимдерди издеген мектептер жана билим берүү мекемелери',
    'home.schools.viewAllSchools': 'Бардык мектептерди көрүү',
    
    // Currency
    'currency.som': 'сом',
    
    // Teacher
    'teacher.nameNotSpecified': 'Аты көрсөтүлгөн эмес',
    'teacher.yearsOfExperience': 'жылдык тажрыйба',
    
    // FAQ
    'faq.title': 'Көп берилүүчү суроолор',
    'faq.subtitle': 'Платформа жөнүндө көп берилүүчү суроолорго жооптор',
    'faq.frequentlyAsked': 'Көп берилүүчү суроолор',
    'faq.createProfile.question': 'Профильди кантип түзүү керек?',
    'faq.createProfile.answer': 'Профиль түзүү үчүн катталуу керек, андан кийин жеке кабинетте бардык керектүү талааларды толтуруу керек. Мугалимдер өздөрүнүн адистигин, жумуш тажрыйбасын, билимин жана жумуш боюнча артыкчылыктарын көрсөтүшөт. Мектептер өздөрүнүн билим берүү мекемеси жөнүндө маалыматты толтурушат.',
    'faq.findSchool.question': 'Ылайыктуу мектепти кантип табуу керек?',
    'faq.findSchool.answer': '"Мектептер" бетинин фильтрлерин колдонуу менен жайгашкан жери, адистиги жана башка параметрлер боюнча билим берүү мекемесин таба аласыз. Мектептердин профилдерин жана алардын ачык вакансияларын көрө аласыз.',
    'faq.applyVacancy.question': 'Вакансияга кантип арыз берүү керек?',
    'faq.applyVacancy.answer': 'Вакансия бетине "Арыз берүү" баскычын басыңыз. Мектеп сиздин арызыңыз жөнүндө билдирүү алат жана сиздин профилиңизди көрө алат. Андан кийин алар сиз менен коңшулаш маек үчүн байланыша алышат.',
    'faq.contactSupport.question': 'Арызга жооп келбесе эмне кылуу керек?',
    'faq.contactSupport.answer': 'Эгер мектеп бир жума ичинде сиздин арызыңызга жооп бербесе, платформадагы чат системасы аркылуу кайталап билдирүү жөнөтө аласыз. Ошондой эле издөөнү улантууну жана сизди кызыктырган башка вакансияларга арыз берүүнү сунуштайбыз.',
    'faq.profileVisibility.question': 'Аккаунтумду кантип өчүрүү керек?',
    'faq.profileVisibility.answer': 'Аккаунтту өчүрүү үчүн профиль параметрлерине барып, "Аккаунтту өчүрүү" бөлүмүн тандап, көрсөтмөлөрдү аткарыңыз. Бул аракет кайталангыс экенин жана бардык маалыматтарыңыз системадан өчүрүлөрүн эске алыңыз.',
    'faq.safety.question': 'Аккаунт түрүмдү өзгөртө аламбы?',
    'faq.safety.answer': 'Жок, аккаунт түрү (мугалим же мектеп) катталуу учурунда тандалат жана өзгөртүлө албайт. Эгер сизге аккаунт түрүн өзгөртүү керек болсо, жаңы эсеп түзүү керек болот.',
    
    // Support
    'support.title': 'Колдоо',
    'support.subtitle': 'Биз сизге каалаган суроолордо жардам берүүгө дайынбыз',
    'support.contactForm': 'Байланыш формасы',
    'support.contactFormDescription': 'Форманы толтуруңуз, биз сиз менен жакында байланышабыз',
    'support.name': 'Сиздин атыңыз',
    'support.namePlaceholder': 'Атыңызды киргизиңиз',
    'support.email': 'Электрондук почта',
    'support.emailPlaceholder': 'your@email.com',
    'support.subject': 'Тема',
    'support.subjectPlaceholder': 'Маселени кыскача сүрөттөңүз',
    'support.message': 'Билдирүү',
    'support.messagePlaceholder': 'Сурооңузду же маселениңизди толук сүрөттөңүз',
    'support.sendMessage': 'Билдирүү жөнөтүү',
    'support.sending': 'Жөнөтүлүүдө...',
    'support.messageSent': 'Билдирүү жөнөтүлдү',
    'support.responseTime': 'Биз сизге жакында жооп беребиз',
    'support.contactInfo': 'Байланыш маалыматы',
    'support.contactInfoDescription': 'Биз менен ыңгайлуу жол менен байланышыңыз',
    'support.emailSupport': 'Электрондук почта колдоосу',
    'support.liveChat': 'Тирүү чат',
    'support.liveChatDescription': 'Жумуш убактысы: 9:00 - 18:00 (Дш-Жм)',
    'support.documentation': 'Документация',
    'support.documentationDescription': 'Пайдалуу макалалар жана көрсөтмөлөр',
    'support.viewDocs': 'Документацияны көрүү',
    'support.commonIssues': 'Көп берилүүчү маселелер',
    'support.howToRegister': 'Кантип катталуу керек?',
    'support.howToCreateProfile': 'Профильди кантип түзүү керек?',
    'support.howToApply': 'Вакансияга кантип арыз берүү керек?',
    'support.accountIssues': 'Аккаунт маселелери',
    
    // Footer
    'footer.information': 'Маалымат',
    'footer.support': 'Колдоо',
    'footer.privacyPolicy': 'Купуялык саясаты',
    'footer.termsOfUse': 'Колдонуу шарттары',
    'footer.contacts': 'Байланыштар',
    'footer.address': 'Бишкек, Кыргыз Республикасы',
    'footer.slogan': 'Өлкө боюнча мугалимдер менен мектептерди байланыштыруу',
    'footer.schoolCatalog': 'Мектептердин каталогу',
    'footer.allRightsReserved': 'Бардык укуктар корголгон',
    
    // Notifications
    'notifications.title': 'Билдирүүлөр',
    'notifications.markAllAsRead': 'Бардыгын окулган деп белгилөө',
    'notifications.markedAsRead': 'Окулган деп белгиленди',
    'notifications.allMarkedAsRead': 'Бардык билдирүүлөр окулган деп белгиленди',
    'notifications.welcomeTitle': 'TeacherConnect KG\'га кош келиңиз!',
    'notifications.welcomeContent': 'Сиздин аккаунтуңуз ийгиликтүү түзүлдү. Ылайыктуу сунуштарды табуу үчүн профилиңизди толтуруңуз.',
    'notifications.newMessageTitle': '{sender} дан жаңы билдирүү',
    'notifications.newMessageContent': 'Физика мугалиминин вакансиясы жөнүндө бир нече суроом бар.',
    
    // Contact Info
    'contact.email': 'teacherconnectkg@gmail.com',
    'contact.phone': '+996 XXX XXX XXX',
    
    // About page
    'about.title': 'Долбоор жөнүндө',
    'about.subtitle': 'TeacherConnect Кыргызстан - мугалимдер менен мектептерди өлкө боюнча байланыштырган платформа',
    'about.mission.title': 'Биздин миссия',
    'about.mission.paragraph1': 'TeacherConnect KG долбоорун Кыргызстандагы мектептерде квалификациялуу мугалимдердин жетишсиздигин чечүү үчүн түздүк. Биздин платформа жумуш же кызматкерлерди табуу процессин жөнөкөй, ачык жана натыйжалуу кылат.',
    'about.mission.paragraph2': 'Биз өлкөдөгү билим берүү системасын жакшыртууга умтулабыз, мектептерди таланттуу мугалимдер менен камсыздап, мугалимдерге алардын жөндөмүнө жана артыкчылыктарына ылайык жумуш табууга жардам беребиз.',
    'about.howItWorks.title': 'Кантип иштейт',
    'about.forTeachers.title': 'Мугалимдер үчүн',
    'about.forTeachers.subtitle': 'Кыялдагы жумушуңузду табыңыз',
    'about.forTeachers.feature1': 'Кесиптик портфолио түзүңүз',
    'about.forTeachers.feature2': 'Актуалдуу жумуш орундарын караңыз',
    'about.forTeachers.feature3': 'Мектептер менен түз байланышта болуңуз',
    'about.forTeachers.feature4': 'Жайгашкан жери жана шарттары боюнча фильтрлөө',
    'about.forSchools.title': 'Мектептер үчүн',
    'about.forSchools.subtitle': 'Идеалдуу талапкерлерди табыңыз',
    'about.forSchools.feature1': 'Мектептин профилин жана жумуш орундарын түзүңүз',
    'about.forSchools.feature2': 'Мугалимдердин анкеталарын караңыз',
    'about.forSchools.feature3': 'Талапкерлерди баалаңыз',
    'about.forSchools.feature4': 'Предметтер боюнча адистерди табыңыз',
    'about.advantages.title': 'Артыкчылыктар',
    'about.advantages.subtitle': 'Эмне үчүн бизди тандашат',
    'about.advantages.feature1': 'Текшерилген анкеталар жана профилдер',
    'about.advantages.feature2': 'Үч тилдеги интерфейс',
    'about.advantages.feature3': 'Ортомчусуз түз байланыш',
    'about.advantages.feature4': 'Регионалдык муктаждыктарга басым',
    'about.learnMore': 'Көбүрөөк билүү',
    'about.joinUs.title': 'Бүгүн бизге кошулуңуз!',
    'about.joinUs.description': 'Кыргызстандын билим берүү системасын жакшыртууга бирге салым кошолу, таланттуу мугалимдерди муктаж мектептер менен байланыштырган платформа. Азыр катталып, ийгиликке жол ачыңыз!',
    'about.faq.title': 'Көп берилүүчү суроолор',
    'about.faq.question1': 'Бул акысызбы?',
    'about.faq.answer1': 'Ооба, платформаны негизги колдонуу мугалимдер үчүн да, мектептер үчүн да акысыз. Келечекте премиум-функциялар кошулат, бирок негизги мүмкүнчүлүктөр акысыз бойдон калат.',
    'about.faq.question2': 'Профилдер кантип текшерилет?',
    'about.faq.answer2': 'Биз документтерди текшерүү системасын колдонобуз. Зарыл документтерди (дипломдор, сертификаттар) жүктөгөндөн кийин, профиль "Текшерилген" статусун алат.',
    'about.faq.question3': 'Платформаны мобилдик телефон менен колдонсо болобу?',
    'about.faq.answer3': 'Ооба, биздин сайт толугу менен мобилдик түзмөктөргө ылайыкталган. Интернетке кире алган бардык түзмөктөрдөн бардык функцияларды колдоно аласыз.',
    'about.faq.viewAll': 'Бардык суроолорду көрүү',
    
    // Schools page
    'schools.title': 'Мектептер',
    'schools.foundCount': '{{count}} мектеп табылды',
    'schools.searchPlaceholder': 'Мектептерди издөө...',
    'schools.filters.city': 'Шаар',
    'schools.filters.district': 'Район',
    'schools.filters.schoolType': 'Мектеп түрү',
    'schools.filters.housing': 'Турак жай',
    'schools.filters.subjects': 'Предметтер',
    'schools.filters.allCities': 'Бардык шаарлар',
    'schools.filters.allDistricts': 'Бардык райондор',
    'schools.filters.allTypes': 'Бардык түрлөрү',
    'schools.filters.allOptions': 'Бардык варианттар',
    'schools.filters.allSubjects': 'Бардык предметтер',
    'schools.filters.withHousing': 'Турак жай менен',
    'schools.filters.withoutHousing': 'Турак жайсыз',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
