// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjbszpnaombmioeeqbzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYnN6cG5hb21ibWlvZWVxYnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjQyOTIsImV4cCI6MjA2NDI0MDI5Mn0.BzysofVLJDGWcVZqXNVF_fDa1DpOD4g1lDy_zxV4rQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);